/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(20) NOT NULL,
    date_of_birth DATE NOT NULL,
    escape_attempts INT,
    neutered BIT,
    weight_kg DECIMAL,
);
 ALTER TABLE animals
 ADD COLUMN  species varchar(50);

 CREATE TABLE owners (
  id INT GENERATED ALWAYS AS IDENTITY,
  full_name VARCHAR(250),
  age INT,
  PRIMARY KEY (id)
 );


 CREATE TABLE species(
  id INT GENERATED ALWAYS AS IDENTITY,
  name VARCHAR(250),
  PRIMARY KEY (id)
 );

 ALTER TABLE animals
 DROP COLUMN species;

ALTER TABLE animals
ADD COLUMN species_id INT,
ADD FOREIGN KEY (species_id) REFERENCES species (id)
ON DELETE CASCADE;

ALTER TABLE animals
ADD COLUMN owner_id INT,
ADD FOREIGN KEY (owner_id) REFERENCES owners (id)
ON DELETE CASCADE;

CREATE TABLE vets(
id INT GENERATED BY DEFAULT AS IDENTITY,
name VARCHAR(250),
age INT,
date_of_graduation DATE,
PRIMARY KEY(id)
);

CREATE TABLE specializations(
species INT NOT NULL,
vets INT NOT NULL,
CONSTRAINT fk_species FOREIGN KEY (species) REFERENCES species(id) ON DELETE CASCADE,
CONSTRAINT fk_vets FOREIGN KEY (vets) REFERENCES vets(id) ON DELETE CASCADE
);

CREATE TABLE visits (
id SERIAL PRIMARY KEY,
animals_id INTEGER,
vets_id INTEGER,
date_of_visit DATE,
CONSTRAINT fk_animals FOREIGN KEY (animals_id) REFERENCES animals(id) ON DELETE CASCADE,
CONSTRAINT fk_vets FOREIGN KEY (vets_id) REFERENCES vets(id) ON DELETE CASCADE
);