/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(20) NOT NULL,
    date_of_birth DATE NOT NULL,
    escape_attempts INT,
    neutered BIT,
    weight_kg DECIMAL,
);
 ALTER TABLE animals
 ADD COLUMN  species varchar(50);
